workdir: "../.." # With this we can specify where should Snakemake look for things relative to this path

rule all:
    input:
        "data/processed/combined_array_normalized.npy",
        "data/processed/session_valid_correct_response.csv"

rule combine_two_arrays:
    input: 
        "data/raw/array1.npy",
        "data/raw/array2.npy"
    output:
        "data/processed/combined_array.npy"
    run:
        import numpy as np
        array1 = np.load(input[0])
        array2 = np.load(input[1])
        data = np.concatenate((array1, array2))
        np.save(output[0], data)

rule standardize_np_array:
    input:
        "data/processed/combined_array.npy"
    output:
        "data/processed/combined_array_standardized.npy"
    run:
        import numpy as np
        input_array = np.load(input[0])
        output_array = (input_array - np.mean(input_array)) / np.std(input_array)
        np.save(output[0], output_array)

rule normalize_np_array:
    input:
        "data/processed/combined_array_standardized.npy"
    output:
        "data/processed/combined_array_normalized.npy"
    run:
        import numpy as np
        input_array = np.load(input[0])
        output_array = input_array - np.min(input_array)
        output_array = output_array / np.max(output_array)

        # Save the normalized array
        np.save(output[0], output_array)


rule valid_csv:
    input:
        "data/raw/session.csv"
    output:
        "data/processed/session_valid.csv"
    shell:
        "python scripts/extract_valid_trials.py {input[0]} {output[0]}"

rule correct_response:
    input:
        "data/processed/session_valid.csv"
    output:
        "data/processed/session_valid_correct_response.csv"
    shell:
        "python scripts/extract_correct_responses.py {input[0]} {output[0]}"




